version: '3'
services:
  web:
    restart: always
    image: node:12.19.0
    working_dir: /src
    ports:
    - "7000:7000"
    volumes:
    - ./:/src
    entrypoint: bash -c "npm install -production && node static.js"
